---
- name: Installation
  apt:
    name: nginx
  notify: Démarrage du service
  become: true

- name: Suppression de la page par défaut
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Redémarrer nginx
  become: true

- name: Création de nginx.conf
  copy:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: Redémarrer nginx
  become: true

- name: Création du/des fichiers de configuration application
  template:
    src: etc/nginx/sites-available/site-configuration.conf.j2
    dest: /etc/nginx/sites-available/{{ item.name }}.conf
    backup: yes
  with_items:
    - "{{ domain }}"
  notify: Redémarrer nginx
  become: true

- name: Activation des sites
  file:
    src: /etc/nginx/sites-available/{{ item.name }}.conf
    dest: /etc/nginx/sites-enabled/{{ item.name }}.conf
    state: link
  with_items:
    - "{{ domain }}"
  notify: Redémarrer nginx
  become: true
...