---
- name: Installation
  npm:
    name: pm2
    global: true
  become: true

- name: Install pm2-logrotate using PM2
  command: pm2 install pm2-logrotate
  changed_when: false

- name: Création fichier ecosystem.config.js
  template:
    src: ecosystem.config.js.j2
    dest: "{{ item.destination }}/ecosystem.config.js"
  with_items:
    - "{{ pm2 }}"
  become: true

- name: Démarre pm2
  command: pm2 start {{ item.destination }}/ecosystem.config.js
  with_items:
    - "{{ pm2 }}"
  when: item.start_application
  notify:
    - Configure pm2 pour execution au reboot
    - Enregistre les processus actuel

- name: Récupère le chemin du home de l'utilisateur
  shell: |
    set -o pipefail
    egrep "^{{ user }}:" /etc/passwd | awk -F: '{ print $6 }'
  args:
    executable: /usr/bin/bash
  changed_when: false
  register: user_home
...