---

- name: Installation du serveur web
  hosts: server
  gather_facts: false

  vars_files:
    - vars/base_vars.yml
    - vars/nodejs.yml
    - vars/pm2.yml
    - vars/nginx.yml
    - vars/mariadb.yml
    - vars/mariadb_secure.yml
    - vars/git.yml
    - vars/parefeu.yml

  roles:
    - base-serveur
    - certbot
    - nginx
    - mariadb
    - git-clone
    - nodejs
    - parefeu
    - pm2
    - reboot
...