---

- name: Installation du serveur web
  hosts: virtual-ubuntu
  gather_facts: false

  vars_files:
    - vars/base_vars.yml
    - vars/nodejs.yml
    - vars/pm2.yml
    - vars/mariadb.yml
    - vars/mariadb_secure.yml

  roles:
    # - base-serveur
    # - certbot
    # - nginx
    - mariadb
    # - nodejs
    # - pm2

...