---

- name: Installation du serveur web
  hosts: server
  gather_facts: false

  vars_files:
    - vars/base_vars.yml

  roles:
    - base-serveur
    - certbot
    - nginx
    - mariadb
    - git-clone
    - nodejs
    - parefeu
    - pm2
    - reboot
...