---
- name: Récupération des sources nodejs
  get_url:
    url: https://deb.nodesource.com/setup_{{ node_version }}.x
    dest: /tmp

- name: Compilation des sources
  command: bash /tmp/setup_{{ node_version }}.x
  changed_when: false
  become: true

- name: Désinstallation de nodejs (si déjà installé)
  apt:
    name: nodejs
    state: absent
  when: node_installed_version.stdout|length > 0
  become: true

- name: Installation de nodejs
  apt:
    name: nodejs
  become: true
...