---
- name: Téléchargement du dépot git
  git:
    repo: >-
      {% if item.auth_methode == 'ssh' %}
      git@
      {%- elif item.auth_methode == 'http' -%}
      http{% if item.http_secure is defined and item.http_secure %}s{% endif %}://
      {%- if item.login is defined -%}
        {{ item.login }}:{{ item.password | default(item.token) }}@
      {%- endif -%}
      {%- endif -%}
      {{ item.git_instance }}
      {%- if item.auth_methode == 'ssh' -%}
      :
      {%- elif item.auth_methode == 'http' -%}
      /
      {%- endif -%}
      {{ item.git_repository }}
    dest: "{{ item.destination_folder }}"
    version: '{{ item.version | default(version) }}'
    accept_hostkey: yes
  register: repo_clone
  failed_when:
    - repo_clone.failed
    - not 'Local modifications exist in repository' in repo_clone.msg
  become: true

- name: Changer l'utilisateur pour le dossier git local
  file:
    state: directory
    recurse: yes
    path: "{{ item.destination_folder }}"
    owner: "{{ item.owner }}"
  when: item.owner is defined
  become: true

- name: Changer le groupe pour le dossier git local
  file:
    state: directory
    recurse: yes
    path: "{{ item.destination_folder }}"
    group: "{{ item.group }}"
  when: item.group is defined
  become: true

- name: Changer les permission pour le dossier git local
  file:
    state: directory
    recurse: yes
    path: "{{ item.destination_folder }}"
    mode: "{{ item.mode }}"
  when: item.mode is defined
  become: true
...