---
- name: Configure pm2 pour execution au reboot
  command: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u {{ user }} --hp {{ user_home.stdout }}
  become: true

- name: Enregistre les processus actuel
  command: pm2 save
...