---
- name: Creation des utilisateurs
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    host: "{{ item.host | default('localhost') }}"
    priv: "{{ item.privilege | default(omit) }}"
    append_privs: "{{ item.append_privileges | default(omit) }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
...