---
- name: tee
  debug:
    var: mariadb_secure

- name: Configure le mot de passe root
  community.mysql.mysql_user:
    login_unix_socket: /run/mysqld/mysqld.sock
    login_user: root
    login_password: ""
    name: root
    password: "{{ mariadb_secure.root_password }}"
    state: present
  become: true

- name: Removes anonymous user account for localhost
  community.mysql.mysql_user:
    name: ''
    host: localhost
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock


...