---
- name: Installation du client mariadb
  apt:
    name: mariadb-client
  when: mariadb_install_client is defined and mariadb_install_client
  become: true

- name: Installation des paquets
  apt:
    name: "{{ item }}"
  with_items:
    - mariadb-server
    - python3-mysqldb
  when: |
    mariadb_install_server is defined
    and mariadb_install_server
    and (mariadb_server_register_version | d() and not mariadb_server_register_version.stdout)
  become: true

- name: Démarrage du service
  service:
    name: mariadb
    state: started
    enabled: true
  when: |
    mariadb_install_server is defined
    and mariadb_install_server
  become: true

- name: Autorise les connections distantes
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    state: present
  when: mariadb_authorize_distant_connection is defined and mariadb_authorize_distant_connection
  notify: Redémarre le service mariadb
  become: true

- name: S'assure que root ne peut pas se connecter depuis des hôtes distants
  mysql_user:
    login_host: localhost
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    name: root
    host: '%'
    state: absent

- name: Vérifie si première installation
  when: |
    mariadb_install_server is defined
    and mariadb_install_server
    and (mariadb_server_register_version | d() and not mariadb_server_register_version.stdout)
  block:
    - name: Configure le mot de passe root
      mysql_user:
        name: root
        host: localhost
        password: "{{ mariadb_root_password }}"
      become: true

    - name: Suppression des utilisateurs anonymes
      mysql_user:
        name: ''
        host_all: true
        state: absent
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Suppression de la base de données de test
      mysql_db:
        db: 'test'
        state: 'absent'
        login_user: root
        login_password: "{{ mariadb_root_password }}"
...