---
- name: Vérifie si mariadb-server est installé
  environment:
    LC_MESSAGES: 'C'
  shell: dpkg-query -W -f='${Version}\n' 'mariadb-server' | grep -v '^$'
  register: mariadb_server_register_version
  changed_when: False
  failed_when: False

- name: Installation
  include_tasks: install.yml

- name: Création utilisateur mariadb
  include_tasks: create_user.yml

- name: Création database mariadb
  include_tasks: create_database.yml
  with_items: "{{ mariadb_database }}"

...

# Voir : https://github.com/bertvv/ansible-role-mariadb/blob/master/tasks/users.yml