---
# les fichier rules.v4 et rules.v6 doivent se terminer par une ligne vide
- name: Création du fichier de configuration du firewall ipv4
  copy:
    src: etc/iptables/rules.v4
    dest: /etc/iptables/rules.v4
  notify: Redémarrer iptables
  become: true

- name: Création du fichier de configuration du firewall ipv6
  copy:
    src: etc/iptables/rules.v6
    dest: /etc/iptables/rules.v6
  notify: Redémarrer iptables
  become: true
...