---
- name: Vérifie si le certificat existe déjà
  stat:
    path: "/etc/letsencrypt/live/{{ item.name }}/cert.pem"
  register: letsencrypt_cert
  become: true

- name: Désactivation de nginx
  service:
    name: nginx
    state: stopped
  register: service_status
  failed_when: "service_status is failed and ('find' not in service_status.msg)"
  when: not letsencrypt_cert.stat.exists
  become: true

- name: Récupération du certificat
  command: >
    certbot certonly --standalone
    --agree-tos
    --email {{ item.certificate.certbot_email }}
    -nd {{ item.name }}
    {% if item.certificate.certbot_staging is defined and item.certificate.certbot_staging %}
    --test-cert
    {% endif %}
  notify: Met en place la tâche cron de renouvellement du certificat
  when: not letsencrypt_cert.stat.exists
  become: true

- name: Réactivation de nginx
  service:
    name: nginx
    state: started
  register: service_status
  failed_when: "service_status is failed and ('find' not in service_status.msg)"
  when: not letsencrypt_cert.stat.exists
  become: true
...