---
- name: Vérifie si le certificat existe déjà
  stat:
    path: "/etc/ssl/certs/{{ item.name }}.crt"
  register: openssl_cert
  become: true

- name: Génération du certificat
  command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout /etc/ssl/private/{{ item.name }}.key
    -out /etc/ssl/certs/{{ item.name }}.crt
    -subj "/C={{ item.certificate.cn | default('FR') }}/ST={{ item.certificate.state | default('France') }}
    /L={{ item.certificate.locality | default('Paris') }}
    /O={{ item.certificate.company | default('.inc') }}
    /OU={{ item.certificate.section | default('') }}
    /CN={{ item.name }}"
  when: not openssl_cert.stat.exists
  become: true

...