---
- name: Vérifier si un certificat certbot est à installer
  set_fact:
    install_certbot: true
  when: item.certificate is defined and item.certificate.type == 'certbot'
  loop: "{{ domain }}"

- name: Installation de certbot
  apt:
    name: certbot
  when: install_certbot
  become: true

- name: Installation certificat certbot
  include_tasks: certificate-certbot.yml
  when: install_certbot
  with_items: "{{ domain }}"

- name: Installation certificat openssl
  include_tasks: certificate-openssl.yml
  when: item.certificate is defined and item.certificate.type == 'openssl'
  with_items: "{{ domain }}"
...